=== phylaxsecurity/scp-registry/scp-spec/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "cve_id",
    "alias",
    "cvss_score",
    "published_date",
    "affected_software",
    "patched_versions",
    "cwe",
    "mitre_attack_ids"
  ],
  "properties": {
    "cve_id": {
      "type": "string"
    },
    "alias": {
      "type": "string"
    },
    "cvss_score": {
      "type": "number"
    },
    "published_date": {
      "type": "string",
      "format": "date"
    },
    "affected_software": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "versions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "versions"
      ]
    },
    "patched_versions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "cwe": {
      "type": "string"
    },
    "mitre_attack_ids": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== phylaxsecurity/scp-registry/resources/CVE-2021-44228/scp.json
{
  "cve_id": "CVE-2021-44228",
  "alias": "Log4Shell",
  "cvss_score": 10.0,
  "published_date": "2021-12-10",
  "affected_software": {
    "name": "Apache Log4j",
    "versions": [
      "2.0-beta9",
      "2.14.1"
    ]
  },
  "patched_versions": [
    "2.15.0",
    "2.16.0",
    "2.17.0"
  ],
  "cwe": "CWE-502",
  "mitre_attack_ids": [
    "T1190",
    "T1059",
    "T1071",
    "T1210"
  ]
}
